export enum EMainIcon {
  '01d' = 'clearDay.svg',
  '01n' = 'clearNight.svg',
  '02d' = 'partlyCloudyDay.svg',
  '02n' = 'partlyCloudyNight.svg',
  '03d' = 'cloudsDay.svg',
  '03n' = 'cloudsNight.svg',
  '04d' = 'cloudsDay.svg',
  '04n' = 'cloudsNight.svg',
  '09d' = 'lightRainDay.svg',
  '09n' = 'lightRainNight.svg',
  '10d' = 'rainfallDay.svg',
  '10n' = 'rainfallNight.svg',
  '11d' = 'thunderstormDay.svg',
  '11n' = 'thunderstormNight.svg',
  '13d' = 'snowfallDay.svg',
  '13n' = 'snowfallNight.svg',
  '50d' = 'partlyCloudyDay.svg',
  '50n' = 'partlyCloudyNight.svg',
}
